// Portfolio homepage
import Image from 'next/image';

const projects = [
  { id: '01', name: 'CloudRevol', category: 'Cloud platform · Work', description: 'Cloud infrastructure made approachable for teams building online.', live: 'https://cloudrevol.com', art: 'cloud', featured: true },
  { id: '02', name: 'CloudRevol Console', category: 'Product console · Work', description: 'The control room for managing CloudRevol services.', live: 'https://console.cloudrevol.com', art: 'console' },
  { id: '03', name: 'CR Guard', category: 'Website security · Work', description: 'A security product for monitoring and protecting WordPress sites.', live: 'https://crguard.cloudrevol.com', art: 'guard' },
  { id: '04', name: 'Reach', category: 'Platform · Work', description: 'A CloudRevol platform built to help businesses move forward.', live: 'https://reach.cloudrevol.com', art: 'reach' },
  { id: '05', name: 'HisabFlow', category: 'SaaS · Personal', description: 'Invoice follow-ups for Pakistani freelancers and small businesses.', live: 'https://hisabflow-app.vercel.app/', art: 'hisab', featured: true },
  { id: '06', name: 'Void Survivor', category: 'Game · Personal', description: 'A fast, browser-based roguelite survival game. Stay alive in the void.', live: 'https://void-survivor-gray.vercel.app', source: 'https://github.com/Mzeeshan127/void-survivor', art: 'game' },
  { id: '07', name: 'AI Blog · Toolstack AI', category: 'AI tools · Personal', description: 'A guide to practical AI tools, reviews, and tutorials for curious builders.', live: 'https://toolstackai.vercel.app/', source: 'https://github.com/Mzeeshan127/Ai-Blog', art: 'blog' },
];

function ProjectArt({ kind }) {
  if (kind === 'cloud') return <div className="art-cloud"><div className="cloud-orbit orbit-one"/><div className="cloud-orbit orbit-two"/><div className="cloud-lockup"><span className="cloud-icon">☁</span><b>cloudrevol</b><small>BUILD ON BETTER CLOUD</small></div><span className="art-chip chip-a">CLOUD / 01</span><span className="art-chip chip-b">INFRASTRUCTURE</span></div>;
  if (kind === 'console') return <div className="art-console"><div className="console-window"><div className="window-bar"><i/><i/><i/><span>console.cloudrevol.com</span></div><div className="console-inner"><aside><b>◈</b><i/><i/><i/><i/></aside><div className="console-content"><small>OVERVIEW / 2026</small><b>Good afternoon.</b><div className="console-stats"><i/><i/><i/></div><div className="console-chart"><span/><span/><span/><span/><span/><span/><span/><span/></div></div></div></div><span className="art-chip console-chip">CONTROL / 02</span></div>;
  if (kind === 'guard') return <div className="art-guard"><div className="guard-ring ring-one"/><div className="guard-ring ring-two"/><div className="guard-shield">⌑</div><div className="guard-alert"><span/> ALL SYSTEMS<br/>PROTECTED</div><span className="art-chip guard-chip">DEFEND / 03</span></div>;
  if (kind === 'reach') return <div className="art-reach"><div className="reach-sun"/><svg viewBox="0 0 420 220" aria-hidden="true"><path d="M-10 178 C76 180 71 42 157 83 S249 197 300 103 S369 48 438 40" fill="none" stroke="#20201c" strokeWidth="2"/><circle cx="157" cy="83" r="8" fill="#fcf9f0" stroke="#20201c" strokeWidth="2"/><circle cx="300" cy="103" r="8" fill="#fcf9f0" stroke="#20201c" strokeWidth="2"/><circle cx="390" cy="48" r="13" fill="#fb6c47" stroke="#20201c" strokeWidth="2"/></svg><span className="reach-word">reach<span>.</span></span><span className="art-chip reach-chip">GROW / 04</span></div>;
  if (kind === 'hisab') return <div className="art-hisab"><div className="hisab-spark">✳</div><div className="invoice-card"><div><small>HISABFLOW</small><b>Invoice<br/>paid.</b></div><div className="invoice-total"><span>COLLECTED</span><strong>Rs 42,500</strong><i>● PAYMENT RECEIVED</i></div><div className="invoice-lines"><i/><i/><i/></div><span className="invoice-stamp">PAID ✓</span></div><span className="art-chip hisab-chip">GET PAID / 05</span></div>;
  if (kind === 'game') return <div className="art-game"><div className="game-stars">✦　·　✧<br/>　·　✦　·</div><div className="game-planet planet-a"/><div className="game-planet planet-b"/><div className="game-core"><span>VOID</span><b>SURVIVOR</b><i>▶ PLAY</i></div><div className="game-grid"/><span className="art-chip game-chip">SURVIVE / 06</span></div>;
  return <div className="art-blog"><div className="blog-heading"><small>THE STUDENT EDITION</small><b>AI, made<br/><em>understandable.</em></b><span>Curiosity, one post at a time ↗</span></div><div className="blog-cards"><div><i>✺</i><small>THE BASICS</small><b>Start with<br/>what matters.</b></div><div><i>↗</i><small>FUTURE / NOW</small><b>Explore<br/>what’s next.</b></div></div><span className="art-chip blog-chip">READ / 07</span></div>;
}

function ProjectCard({ project }) {
  const projectUrl = project.live || project.source;
  return <article className={`project-card project-${project.art} ${project.featured ? 'project-featured' : ''}`}>
    <a className="project-art-link" href={projectUrl} target="_blank" rel="noreferrer" aria-label={`Open ${project.name}`}><ProjectArt kind={project.art}/></a>
    <div className="project-info"><div><p>{project.id} <span>·</span> {project.category}</p><h3>{project.name}</h3><p className="project-description">{project.description}</p></div><div className="project-actions">{project.live && <a href={project.live} target="_blank" rel="noreferrer">Live site <span>↗</span></a>}{project.source && <a href={project.source} target="_blank" rel="noreferrer">{project.live ? 'Source' : 'GitHub'} <span>↗</span></a>}</div></div>
  </article>;
}

export default function Home() {
  return <main id="top" className="portfolio">
    <header className="site-header"><a href="#top" className="wordmark"><span>z.</span>zeeshan surti</a><nav><a href="#work">Selected work <sup>07</sup></a><a href="#experience">Experience</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-cta" href="mailto:zeeshansurti127@gmail.com">Let’s talk <span>↗</span></a></header>

    <section className="hero">
      <div className="hero-copy"><p className="overline"><span/> SOFTWARE DEVELOPER <i>·</i> 5 YEARS’ EXPERIENCE <i>·</i> KARACHI, PK</p><h1>Building web<br/>products with<br/><span className="hero-italic">purpose.</span></h1><p className="hero-intro">I’m <strong>Muhammad Zeeshan Surti</strong>, a software developer with five years of experience. I build cloud products at CloudRevol and ship useful products of my own.</p><div className="hero-links"><a className="button-dark" href="#work">Explore selected work <span>↓</span></a><a href="mailto:zeeshansurti127@gmail.com" className="text-link">Get in touch <span>↗</span></a></div></div>
      <div className="hero-art" aria-label="Portrait of Muhammad Zeeshan with graphic accents"><div className="hero-art-grid"/><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="hero-portrait"><Image src="/zeeshan-portrait.jpg" alt="Muhammad Zeeshan" fill priority sizes="(max-width: 650px) 78vw, 300px"/></div><div className="hero-flower">✳</div><div className="hero-sticker"><b>IDEAS</b><small>INTO IMPACT</small><span>✳</span></div><div className="hero-caption">INDEPENDENT THINKING<br/>SINCE ALWAYS — 01/26</div><span className="hero-spark spark-a">✦</span><span className="hero-spark spark-b">✳</span></div>
      <div className="hero-index"><span>SCROLL TO EXPLORE</span><span>↓</span></div>
    </section>

    <div className="ticker" aria-label="Build thoughtfully, make useful things"><div>BUILD THOUGHTFULLY <i>✳</i> MAKE USEFUL THINGS <i>✳</i> STAY CURIOUS <i>✳</i> BUILD THOUGHTFULLY <i>✳</i> MAKE USEFUL THINGS <i>✳</i> STAY CURIOUS <i>✳</i></div></div>
    <section className="proof-strip" aria-label="Experience highlights"><div className="proof-years"><strong>05</strong><span>YEARS BUILDING<br/>FOR THE WEB</span></div><div><span>CURRENTLY BUILDING AT</span><strong>CloudRevol <i>↗</i></strong></div><div><span>FOCUS</span><strong>Product UI · Cloud · SaaS</strong></div><div><span>ALSO BUILDING</span><strong>HisabFlow · Void Survivor</strong></div></section>

    <section id="work" className="work-section"><div className="section-heading"><div><p className="overline">A FEW THINGS I’VE MADE <span>✳</span></p><h2>Selected<br/><em>work.</em></h2></div><p className="section-note">From work that serves thousands to ideas that started as a weekend experiment. Every project has a story—tap through and take a look.</p><span className="work-count">07<span> / 07</span></span></div>
      <div className="project-grid">{projects.map(project=><ProjectCard key={project.id} project={project}/>)}</div>
    </section>

    <section id="experience" className="experience-section"><div className="experience-heading"><p className="overline">05 YEARS · SOFTWARE DEVELOPMENT</p><h2>Product work<br/><em>in the real world.</em></h2><p>I care about the details people feel: a clear interface, a dependable flow, and a product that earns its place in someone’s day.</p></div><div className="experience-card"><div className="experience-card-top"><span className="experience-dot"/> CURRENT ROLE <span className="experience-now">NOW</span></div><h3>Software Developer</h3><p className="company-name">CloudRevol <span>· Karachi, Pakistan</span></p><p className="experience-description">Building and improving cloud products across the CloudRevol platform, console, security, and Reach experiences.</p><div className="experience-projects"><a href="https://cloudrevol.com" target="_blank" rel="noreferrer">Cloud platform ↗</a><a href="https://console.cloudrevol.com" target="_blank" rel="noreferrer">Console ↗</a><a href="https://crguard.cloudrevol.com" target="_blank" rel="noreferrer">CR Guard ↗</a><a href="https://reach.cloudrevol.com" target="_blank" rel="noreferrer">Reach ↗</a></div><div className="experience-foot"><span>INDEPENDENTLY, I BUILD</span><b>HisabFlow&nbsp; · &nbsp;Void Survivor&nbsp; · &nbsp;AI Blog</b></div></div></section>

    <section className="toolkit-section"><div><p className="overline">MY TOOLKIT</p><h2>Tools I build<br/><em>with every day.</em></h2></div><div className="toolkit-list">{[['01','React'],['02','Next.js'],['03','JavaScript'],['04','Tailwind CSS'],['05','Supabase'],['06','Git & GitHub']].map(([n,t])=><div key={n}><span>{n}</span><b>{t}</b><i>↗</i></div>)}</div></section>

    <section id="about" className="about-section"><div className="about-stamp">✳<span>GOOD IDEAS<br/>DESERVE<br/>GOOD CRAFT</span></div><div><p className="overline">A LITTLE ABOUT ME</p><h2>Curious mind.<br/><em>Builder’s hands.</em></h2></div><div className="about-copy"><p>I’m Muhammad Zeeshan Surti, a software developer based in Karachi. I enjoy taking something complicated and making it feel clear, useful, and a little bit delightful.</p><p>At CloudRevol, I contribute to products used by real teams. On my own time, I build SaaS ideas, a survival game, and an AI blog for students. I like the whole journey: the first sketch, the details, and the moment it finally works.</p><div className="about-tags"><span>PRODUCT THINKING</span><span>WEB DEVELOPMENT</span><span>CLOUD PLATFORMS</span><span>INDEPENDENT BUILDS</span></div></div></section>

    <section id="contact" className="contact-section"><div className="contact-doodle">↗</div><p className="overline">HAVE SOMETHING IN MIND?</p><h2>Let’s make<br/><em>it matter.</em></h2><a className="contact-email" href="mailto:zeeshansurti127@gmail.com">zeeshansurti127@gmail.com <span>↗</span></a><p className="contact-caption">Good projects start with a conversation. Tell me what you’re dreaming up.</p><div className="social-links"><a href="https://www.linkedin.com/in/muhammad-zeeshan-412052207/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/Mzeeshan127" target="_blank" rel="noreferrer">GitHub ↗</a><a href="mailto:zeeshansurti127@gmail.com">Email ↗</a></div></section>

    <footer className="site-footer"><a href="#top" className="wordmark"><span>z.</span>zeeshan surti</a><p>MADE WITH CURIOSITY · © {new Date().getFullYear()} MUHAMMAD ZEESHAN</p><a href="#top">BACK TO TOP ↑</a></footer>
  </main>;
}
